ckan/patches/ckanext-harvest/ckanext/harvest/views.py
# -*- coding: utf-8 -*-

import ckantoolkit as tk
from flask import Blueprint, make_response

import ckanext.harvest.utils as utils

# IDatasetForm provides a "harvest" blueprint for the package type harvest.
# We name the extension blueprint "harvester" to avoid clashing of names.
harvester = Blueprint("harvester", __name__)


@harvester.before_request
def before_request():
    tk.c.dataset_type = utils.DATASET_TYPE_NAME


def delete(id):
    return utils.delete_view(id)


def refresh(id):
    return utils.refresh_view(id)


def admin(id):
    return utils.admin_view(id)


def about(id):
    return utils.about_view(id)


def clear(id):
    return utils.clear_view(id)


def job_list(source):
    return utils.job_list_view(source)


def job_show_last(source):
    return utils.job_show_last_view(source)


def job_show(source, id):
    return utils.job_show_view(id)


def job_abort(source, id):
    return utils.job_abort_view(source, id)


def object_show(id, ref_type):
    (response, content) = utils.object_show_view(id, ref_type, make_response())
    response.set_data(content)
    return response


harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/delete/<id>",
    view_func=delete,
)
harvester.add_url_rule("/" + utils.DATASET_TYPE_NAME + "/refresh/<id>",
                       view_func=refresh,
                       methods=(u'POST', u'GET'))
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/admin/<id>",
    view_func=admin,
)
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/about/<id>",
    view_func=about,
)
harvester.add_url_rule("/" + utils.DATASET_TYPE_NAME + "/clear/<id>",
                       view_func=clear,
                       methods=(u'POST', u'GET'))
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/<source>/job",
    view_func=job_list,
)
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/<source>/job/last",
    view_func=job_show_last,
)

harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/<source>/job/<id>",
    view_func=job_show,
)
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/<source>/job/<id>/abort",
    view_func=job_abort,
)
harvester.add_url_rule(
    "/" + utils.DATASET_TYPE_NAME + "/object/<id>",
    view_func=object_show,
    defaults={"ref_type": "object"},
)
harvester.add_url_rule(
    "/dataset/harvest_object/<id>",
    view_func=object_show,
    defaults={"ref_type": "dataset"},
)


def get_blueprints():
    return [harvester]

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/about.html
{% extends "source/read_base.html" %}

{% block primary_content_inner %}
  <section class="module-content">
    <h1>{{ harvest_source.title or harvest_source.name }}</h1>
    {% if harvest_source.notes %}
      <p>{{ h.markdown_extract(harvest_source.notes)|urlize }}</p>
    {% else %}
      <p class="empty">{{ _('There is no description for this harvest source') }}</p>
    {% endif %}
  </section>
  {% snippet "package/snippets/additional_info.html", pkg_dict=harvest_source %}
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/admin.html
{% extends "source/admin_base.html" %}

{% block primary_content_inner %}
  <section class="module-content">
    <h1>{{ _('Last Harvest Job') }}</h1>
    {% if harvest_source.status and harvest_source.status.last_job %}
      {% snippet "snippets/job_details.html", job=harvest_source.status.last_job %}
      <div class="form-actions">
          <a href="{{ h.url_for('harvester.job_show_last', source=harvest_source.name) }}" class="btn pull-right btn-default">
          <i class="fa fa-briefcase icon-briefcase"></i>
          {{ _('View full job report')  }}
        </a>
      </div>
    {% else %}
      <p class="empty">{{ _('No jobs yet for this source') }}</p>
    {% endif %}
  </section>
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/admin_base.html
{% extends "source/read_base.html" %}

{% block breadcrumb_content_root_selected %}{% endblock %}

{% block breadcrumb_content %}
  {{ super() }}
  <li class="active"><a href="">{{ _('Admin') }}</a></li>
{% endblock %}

{% block content_action %}
  <div class="content_action btn-group">
  {% if harvest_source.status and harvest_source.status.last_job and (harvest_source.status.last_job.status == 'New' or harvest_source.status.last_job.status == 'Running') %}
    <a class="btn btn-default disabled" rel="tooltip" title="There already is an unrun job for this source"><i class="fa fa-lg fa-refresh icon-refresh icon-large"></i> Reharvest</a>
  {% else %}
    {% set locale = h.dump_json({'content': _('This will re-run the harvesting for this source. Any updates at the source will overwrite the local datasets. Sources with a large number of datasets may take a significant amount of time to finish harvesting. Please confirm you would like us to start reharvesting.')}) %}
      <a href="{{ h.url_for('harvester.refresh', id=harvest_source.id) }}" class="btn btn-default" data-module="confirm-action" data-module-i18n="{{ locale }}"
         title="{{ _('Start a new harvesting job for this harvest source now') }}">
        <i class="fa fa-refresh icon-refresh"></i>
        {{ _('Reharvest') }}
      </a>
  {% endif %}
  {% if harvest_source.status and harvest_source.status.last_job and (harvest_source.status.last_job.status == 'Running') %}
      <a href="{{ h.url_for('harvester.job_abort', source=harvest_source.name, id=harvest_source.status.last_job.id) }}" class="btn btn-default" title="Stop this Job">
        <i class="fa fa-ban icon-ban-circle"></i>
        {{ _('Stop') }}
      </a>
  {% endif %}
    {% set locale = h.dump_json({'content': _('Warning: This will remove all datasets for this source, as well as all previous job reports. Are you sure you want to continue?')}) %}
      <a href="{{ h.url_for('harvester.clear', id=harvest_source.id) }}" class="btn btn-default" data-module="confirm-action" data-module-i18n="{{ locale }}"
         title="{{ _('Delete all harvest jobs and existing datasets from this source') }}">
        {{ _('Clear') }}
      </a>
       <a href="{{ h.url_for('{0}.read'.format(c.dataset_type), id=harvest_source.id) }}" class="btn btn-default">
        <i class="fa fa-eye eye-open"></i>
        {{ _('View harvest source') }}
      </a>
    </div>
{% endblock %}

{% block page_header_tabs %}
  {{ h.build_nav_icon('harvester.admin', _('Dashboard'), id=harvest_source.name, icon='dashboard') }}
  {{ h.build_nav_icon('harvester.job_list', _('Jobs'), source=harvest_source.name, icon='reorder') }}
  {{ h.build_nav_icon(c.dataset_type ~ '.edit', _('Edit'), id=harvest_source.name, icon='edit') }}
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/base.html
{% extends "page.html" %}
{% set harvest_source = harvest_source or h.get_harvest_source() %}
{% if harvest_source %}
    {% set authorized_user = h.check_access('harvest_source_update', {'id':harvest_source.id }) %}
{% else %}
    {% set authorized_user = h.check_access('harvest_source_create') %}
{% endif %}

{% block subtitle %}{{ harvest_source.title or harvest_source.name }}{% endblock %}

{% block breadcrumb_content_root_selected %} class="active"{% endblock %}

{% block breadcrumb_content %}
  {% if harvest_source.organization %}
    {% set org = harvest_source.organization %}
    <li>{{ h.nav_link(_('Organizations'), named_route='organizations_index') }}</li>
    <li>{{ h.nav_link(org.title or org.name|truncate(10), named_route='organization_read', id=org.name) }}</li>
    <li>{{ h.nav_link(_('Harvest Sources'), named_route='{0}_search'.format(c.dataset_type)) }}</li>
    <li{{ self.breadcrumb_content_root_selected() }}>{{ h.nav_link(harvest_source.title|truncate(10), named_route='{0}_read'.format(c.dataset_type), id=harvest_source.name) }}</li>
  {% else %}
    <li>{{ h.nav_link(_('Harvest Sources'), named_route='{0}_search'.format(c.dataset_type)) }}</li>
    <li{{ self.breadcrumb_content_root_selected() }}>{{ h.nav_link(harvest_source.title|truncate(30), named_route='{0}_read'.format(c.dataset_type), id=harvest_source.name) }}</li>
  {% endif %}
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/edit.html
{% extends "source/admin_base.html" %}

{% block subtitle %}{{ _('Edit harvest source') }}{% endblock %}

{% block primary_content_inner %}

  <div class="module-content">
    {% block form %}
      {{- h.snippet(form_snippet, c=c, **form_vars) -}}
    {% endblock %}
  </div>
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/new.html
{% extends "source/admin_base.html" %}

{% block breadcrumb_content %}
  <li>{{ h.nav_link(_('Harvest Sources'), named_route='{0}_search'.format(c.dataset_type)) }}</li>
  <li class="active">{{ h.nav_link(_('Create Harvest Source'), named_route='{0}_new'.format(c.dataset_type)) }}</li>
{% endblock %}

{% block actions_content %}
{% endblock %}

{% block subtitle %}{{ _('Create harvest source') }}{% endblock %}

{% block primary_content %}
  <section class="module">
    <div class="module-content">
      {{- h.snippet(form_snippet, c=c, **form_vars) -}}
    </div>
  </section>
{% endblock %}

{% block secondary_content %}
  <section class="module module-narrow">
    <h2 class="module-heading"><i class="fa fa-lg fa-info-circle icon-large icon-info-sign"></i> {{ _('Harvest sources') }}</h2>
    <div class="module-content">
      <p>
        {% trans %}
        Harvest sources allow importing remote metadata into this catalog.
        Remote sources can be other catalogs such as other CKAN instances, CSW
        servers or Web Accessible Folders (WAF) (depending on the actual
        harvesters enabled for this instance).
        {% endtrans %}
      </p>
    </div>
  </section>
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/new_source_form.html
{% import 'macros/form.html' as form %}

{% asset 'harvest-extra-field/main' %}

<form id="source-new" class="form-horizontal" method="post" >

  {% block errors %}{{ form.errors(error_summary) }}{% endblock %}

  {% call form.input('url', id='field-url', label=_('URL'), value=data.url, error=errors.url, classes=['control-full', 'control-large']) %}
      <span class="info-block">
        {{ _('This should include the http:// part of the URL') }}
      </span>
  {% endcall %}

  {{ h.csrf_input() if 'csrf_input' in h }}

  {{ form.input('title', id='field-title', label=_('Title'), placeholder=_('eg. A descriptive title'), value=data.title, error=errors.title, classes=['control-full'], attrs={'data-module': 'slug-preview-target'}) }}

  {% set prefix = 'harvest' %}
  {% set domain = h.url_for('{0}.read'.format(c.dataset_type), id='', qualified=true) %}
  {% set domain = domain|replace("http://", "")|replace("https://", "") %}
  {% set attrs = {'data-module': 'slug-preview-slug', 'data-module-prefix': domain, 'data-module-placeholder': '<harvest-source>'} %}

  {{ form.prepend('name', id='field-name', label=_('Name'), prepend=prefix, placeholder=_('eg. my-dataset'), value=data.name, error=errors.name, attrs=attrs) }}

  {{ form.markdown('notes', id='field-notes', label=_('Description'), value=data.notes, error=errors.notes) }}

  <div class="harvest-types form-group control-group">
    <label class="control-label">Source type</label>
    <div class="controls">
      {% for harvester in h.harvesters_info() %}
        {% set checked = False %}
        {# select first option if nothing in data #}
        {% if data.source_type == harvester['name'] or (not data.source_type and loop.first) %}
           {% set checked = True %}
        {% endif %}
        <label class="radio">
          <input type="radio" name="source_type" value="{{ harvester['name'] }}" {{ "checked " if checked }} data-module="harvest-type-change">
          {{ harvester['title'] }}
          <i class="fa fa-question-circle icon-question-sign muted" title="{{ harvester['description'] }}" data-bs-toggle="tooltip" data-toggle="tooltip"></i>
        </label>
      {% endfor %}
    </div>
  </div>

  {{ form.select('frequency', id='field-frequency', label=_('Update frequency'), options=h.harvest_frequencies(), selected=data.frequency, error=errors.frequency) }}

  {% block extra_config %}
  {{ form.textarea('config', id='field-config', label=_('Configuration'), value=data.config, error=errors.config) }}
  {% endblock extra_config %}

  {# if we have a default group then this wants remembering #}
  {% if data.group_id %}
    <input type="hidden" name="groups__0__id" value="{{ data.group_id }}" />
  {% endif %}

  {% set dataset_is_draft = data.get('state', 'draft').startswith('draft') or data.get('state', 'none') ==  'none' %}
  {% set dataset_has_organization = data.owner_org or data.group_id %}
  {% set organizations_available = h.organizations_available('create_dataset') %}
  {% set user_is_sysadmin = h.check_access('sysadmin') %}
  {% set show_organizations_selector = organizations_available and (user_is_sysadmin or dataset_is_draft) %}

  {% if show_organizations_selector %}
    {% set existing_org = data.owner_org %}
    <div class="control-group form-group">
      <label for="field-organizations" class="control-label">{{ _('Organization') }}</label>
      <div class="controls">
        <select id="field-organizations" name="owner_org" data-module="autocomplete">
          <option value="" {% if not selected_org and data.id %} selected="selected" {% endif %}>{{ _('No organization') }}</option>
          {% for organization in organizations_available %}
            {# get out first org from users list only if there is not an existing org #}
            {% set selected_org = (existing_org and existing_org == organization.id) or (not existing_org and not data.id and organization.id == organizations_available[0].id) %}
            <option value="{{ organization.id }}" {% if selected_org %} selected="selected" {% endif %}>{{ organization.name }}</option>
          {% endfor %}
        </select>
      </div>
    </div>
  {% endif %}

  {% if data.get('id', None) and h.check_access('harvest_source_delete', {'id': data.id}) and data.get('state', 'none') == 'deleted' %}
    <div class="control-group">
      <label for="field-state" class="control-label">{{ _('State') }}</label>
      <div class="controls">
        <select id="field-state" name="state">
          <option value="active" {% if data.get('state', 'none') == 'active' %} selected="selected" {% endif %}>{{ _('Active') }}</option>
          <option value="deleted" {% if data.get('state', 'none') == 'deleted' %} selected="selected" {% endif %}>{{ _('Deleted') }}</option>
        </select>
      </div>
    </div>
  {% endif %}

  <p class="form-actions">
    {% block delete_button %}
      {% if data.get('id', None) and h.check_access('harvest_source_delete', {'id': data.id}) and not data.get('state', 'none') == 'deleted' %}
        {% set locale_delete = h.dump_json({'content': _('This will flag the source as deleted but keep all its datasets and previous jobs. Are you sure you want to delete this harvest source?')}) %}
        {% set locale_clear = h.dump_json({'content': _('Warning: Apart from deleting this source, this command will remove all its datasets, as well as all previous job reports. Are you sure you want to continue?')}) %}
  <div class="dropdown btn-group">
    <a href="#" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" data-toggle="dropdown">
      {{ _('Delete') }}
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <a href="{% url_for 'harvest_delete', id=data.name %}" data-module="confirm-action" data-module-i18n="{{ locale_delete }}">
          {{ _('Delete source') }}
        </a>
      </li>
      <li>
        <a href="{% url_for 'harvest_delete', id=data.name %}?clear=True" data-module="confirm-action" data-module-i18n="{{ locale_clear }}">
          {{ _('Delete and clear source') }}
        </a>
      </li>
    </ul>
  </div>
      {% endif %}
    {% endblock %}

    <input id="save" name="save" value="Save" type="submit" class="btn btn-primary pull-right">
  </p>

</form>

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/read.html
{% extends "source/read_base.html" %}

{% block primary_content_inner %}
  <section class="module-content">
    <h1 class="hide-heading">{{ _('Datasets') }}</h1>
    {{ h.package_list_for_source(harvest_source.id)  }}
  </section>
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/read_base.html
{% extends "source/base.html" %}

{% block secondary_content %}
  <div class="module context-info">
    <section class="module-content">
      <h1 class="heading">{{ harvest_source.title }}</h1>
      {% if harvest_source.notes %}
        <p>
          {{ h.markdown_extract(harvest_source.notes, 180) }}
          {{ h.nav_link(_('read more'), named_route='harvester.about', id=harvest_source.name) }}
        </p>
      {% else %}
        <p class="empty">{{ _('There is no description for this harvest source') }}</p>
      {% endif %}
      <div class="nums">
        <dl>
            <dt>{{ _('Datasets') }}</dt>
            <dd>{{ h.package_count_for_source(harvest_source.id) }}</dd>
        </dl>
      </div>
    </section>
  </div>
{% endblock %}

{% block primary_content %}
  <article class="module">
    {% block page_header %}
      <header class="module-content page-header">
        {% block content_action %}
          <div class="content_action">
            {% if h.check_access('harvest_source_update', {'id':harvest_source.id }) %}
              {{ h.nav_link(_('Admin'), named_route='harvester.admin', id=harvest_source.name, class_='btn btn-primary', icon='wrench')}}
            {% endif %}
          </div>
        {% endblock %}
        <ul class="nav nav-tabs">
          {% block page_header_tabs %}
          {{ h.build_nav_icon(c.dataset_type ~ '.read', _('Datasets'), id=harvest_source.name, icon='sitemap') }}
          {{ h.build_nav_icon('harvester.about', _('About'), id=harvest_source.name, icon='info-sign') }}
          {% endblock %}
        </ul>
      </header>
    {% endblock %}
    {% block primary_content_inner %}{% endblock %}
  </article>
{% endblock %}

ckan/patches/ckanext-harvest/ckanext/harvest/templates/source/search.html
{% extends "page.html" %}

{% block subtitle %}{{ _("Harvest sources") }}{% endblock %}


{% block breadcrumb_content %}
  <li class="active">{{ h.nav_link(_('Harvest Sources'), named_route='{0}_search'.format(c.dataset_type)) }}</li>
{% endblock %}


{% block primary_content %}
    <section class="module">
      <div class="module-content">
        {% block page_primary_action %}
          <div class="page_primary_action">
            {{ h.snippet('snippets/add_source_button.html', dataset_type=c.dataset_type) }}
          </div>
        {% endblock %}

        {% set facets = {
          'fields': c.fields_grouped,
          'search': c.search_facets,
          'titles': c.facet_titles,
          'translated_fields': c.translated_fields,
          'remove_field': c.remove_field }
        %}
        {% set sorting = [
          (_('Relevance'), 'score desc, metadata_modified desc'),
          (_('Name Ascending'), 'title_string asc'),
          (_('Name Descending'), 'title_string desc'),
          (_('Last Modified'), 'metadata_modified desc'),
          (_('Popular'), 'views_recent desc') if g.tracking_enabled else (false, false) ]
        %}
        {% snippet 'snippets/search_form.html', type='harvest', query=c.q, sorting=sorting, sorting_selected=c.sort_by_selected, count=c.page.item_count, facets=facets, show_empty=request.args, error=c.query_error, placeholder=_("Search harvest sources...") %}

        {{ h.snippet('snippets/source_list.html', sources=c.page.items, show_organization=true) }}

      </div>

      {{ c.page.pager(q=c.q) }}
    </section>

    {% endblock %}



{% block secondary_content %}
  {% for facet in c.facet_titles %}
      {{ h.snippet('snippets/facet_list.html', title=c.facet_titles[facet], name=facet, alternative_url=h.url_for('{0}.search'.format(c.dataset_type))) }}
  {% endfor %}
{% endblock %}